### ISSUE TITLE
Hover animations

### ISSUE THREAD

**Issue by Shrewbi** [OrangeNote/RuneBook#32]
Add hover animations for runes to display names and their description. Also a description for these 
![image](https://user-images.githubusercontent.com/9056155/37247356-cd78b802-24b9-11e8-83e9-3c414322fa8f.png)

**Comment by OrangeNote** [comment]
So, I'm planning to add tooltips to buttons.

For runes, I only managed to show names, but not descriptions, because of technical limitations of the UI framework I'm using (or maybe because I don't know how to make it work, if there is actually a way to do it). So I'm flagging this issue with 'help-wanted'.

**Comment by OrangeNote** [comment]
Done!
