### ISSUE TITLE
[Suggestion] Runes on auto-pilot

### ISSUE THREAD

**Issue by Constant-ine** [OrangeNote/RuneBook#39]
So here's a suggestion, there could be an option to disable auto-pilot, what that would do is use the Auto select feature to find which champion you are playing and automatically apply the HW or MF runes (option in the settings) and from what provider the user wants as well (champion.gg, runes LoL etc) the provider would be selectable in the settings as well. Basically you wouldn't have to touch your runes and it'd all be done automatically, any thoughts? Also another little suggestion, if a user enables auto-select, have that be saved so the next time RuneBook is launched auto-select is already enabled rather than having to enable it again.

**Comment by raitono** [comment]
I think it's a nice idea. Instead of having so many options to setup though, perhaps there could simply be a favorite or "star" button which would set a particular page as being auto selected.

This would expand the feature to include custom sets too. And since you can link your local pages to the pages from the sites, you simply have to bring the page locally and then star it to have it auto applied.

I also agree that the auto-select toggle should be remembered, but that's best mentioned in another topic.

**Comment by OrangeNote** [comment]
I already discussed this feature with the community and friends. As a design principle, I think users should always be aware of their choices. LoL is a constantly evolving game and it always requires a continuous adaptation of strategies to execute. And because of that I don't want that someone (or something) chooses for you instead. I know that even Riot won't allow this type of forced interactions without user intervention. Automatic page selection was the original idea when I started developing RuneBook. But I realized that this app is already in a gray area and I want it to comply with Riot policies as far as possible. So I won't add automatic page selection.

Remembering user preference for the auto select switch is already planned; consider it done for the next release.

Leaving this issue open, if there's something else you wanted to ask 🙂

**Comment by Constant-ine** [comment]
Nope you've answered all my questions, great software btw, thank you for the prompt reply :)

**Comment by OrangeNote** [comment]
@raitono Didn't see your answer before posting mine. So originally I had a favorite system implemented, and that was the way I was going to address automatic page selection. One fav per champion, and you could only fav local pages (that means you had to bookmark remote pages before setting them as fav). But then I discarded the idea for the reasons I mentioned above.

@Constant-ine thanks for feedback!
