### ISSUE TITLE
Game client anti-cheat changes going live

### ISSUE THREAD

**Issue by infernuspt** [OrangeNote/RuneBook#46]
Will Runebook be hit by this? Can you get a new confirmation that it's ok to use? I've been using for a good time now but after this statements i'm kinda afraid to use it.

**Comment by OrangeNote** [comment]
Hi, I'm aware of these anti-cheats changes, and I can assure you they will not affect the way RuneBook works. You can still use RuneBook without worrying about being punished by Riot.

Those changes affect the game and not the launcher/client. RuneBook doesn't interfere with the game, so it's still safe to use. More generally, if one day Riot decides that RuneBook (or other similar external programs) is no longer an acceptable tool, they will contact the author (me in this case) to find a way to solve the problem (usually compromise of features if feasible, or complete shutdown of the project if there are no options left). They won't immediately ban users, only because they suddenly changed their policy about third party software. They theoretically can by terms of service, but I'm sure they won't without context.

So, have fun with RuneBook 😄
